[Reading 21 lines from start (total: 21 lines, 0 remaining)]

(function(){
const M=window.RESEARCH_META||{},root=document.querySelector('.w');if(!root)return;
const esc=x=>String(x??'—').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const pct=x=>x==null?'—':(100*(+x)).toFixed(1)+'%';
const ruleText=r=>r.feature?esc(r.feature)+' '+esc(r.op)+' '+esc(r.value):Object.entries(r).map(([k,v])=>esc(k)+' = '+esc(v)).join('<br>');
const tabs=document.createElement('div');tabs.className='tabs';tabs.innerHTML='<button data-tab="session" class="active">Sesión intradía</button><button data-tab="episodes">Episodios</button><button data-tab="hyp">Hipótesis</button><button data-tab="pros">Validación prospectiva</button><button data-tab="lab">Discovery Lab</button>';
root.insertBefore(tabs,root.children[1]);
const banner=document.createElement('div');banner.className='research-banner';banner.innerHTML='<b>Sesión de descubrimiento: '+esc(M.discovery_session)+'</b> · Los resultados de esta fecha son diagnósticos y no cuentan como evidencia prospectiva.';root.insertBefore(banner,tabs.nextSibling);
const header=root.querySelector('header'),cards=root.querySelector('#cards'),grid=root.querySelector('.grid'),compare=document.querySelector('#compare')?.closest('.panel'),foot=root.querySelector('.foot');
const session=[header,cards,grid,compare,foot].filter(Boolean);session.forEach(x=>x.dataset.tabgroup='session');
const make=(id,html)=>{let d=document.createElement('div');d.className='tabpage';d.dataset.tabgroup=id;d.innerHTML=html;root.appendChild(d);return d};
const hyp=make('hyp','<div class="panel"><h2>Hipótesis y candidatos</h2><div class="explain"><b>Separación metodológica:</b> H01/H02 están congeladas y se evalúan prospectivamente. H03/H04/H05 nacieron del 2-oct y siguen sin congelar.</div><div class="hypgrid" id="hypgrid"></div></div>');
const pros=make('pros','<div class="panel"><h2>Validación prospectiva</h2><div class="explain"><b>Regla:</b> esta pestaña excluye automáticamente todo dato del 2-oct o anterior. Cero observaciones es un resultado correcto hasta que lleguen sesiones nuevas.</div><div class="hypgrid" id="prosgrid"></div></div>');
const lab=make('lab','<div class="panel"><h2>Discovery Lab</h2><div class="explain"><b>Uso:</b> aquí mostramos combinaciones retrospectivas para generar hipótesis, no para afirmar rendimiento futuro. Baseline = frecuencia del evento en datos observables; lift = tasa de la combinación / baseline.</div><div id="labgrid"></div></div>');
document.getElementById('hypgrid').innerHTML=(M.hypotheses||[]).map(h=>'<div class="hypcard '+h.kind+'"><div class="hyphead"><b>'+esc(h.id)+'</b><span class="side '+h.side.toLowerCase()+'">'+h.side+' · '+h.horizon_min+'m</span></div><div class="state">'+esc(h.status)+'</div><div class="rules">'+(Array.isArray(h.rules)?h.rules.map(ruleText).join('<br>'):ruleText(h.rules))+'</div>'+(h.discovery_episode?'<div class="metricline"><span>Episodios discovery</span><b>'+h.discovery_episode.tp_first+'/'+h.discovery_episode.tp_sl_decided+' TP-first</b></div>':'')+'</div>').join('');
document.getElementById('prosgrid').innerHTML=(M.hypotheses||[]).map(h=>{let e=(M.prospective||{})[h.id];if(h.kind==='frozen')return '<div class="hypcard frozen"><b>'+esc(h.id)+'</b><div class="state">TRACKER PROSPECTIVO EXISTENTE</div><div class="hint">Se mantiene separado del evaluador exploratorio para no alterar H01/H02.</div></div>';return '<div class="hypcard candidate"><b>'+esc(h.id)+'</b><div class="metricline"><span>Días prospectivos</span><b>'+(e?.prospective_days??0)+'</b></div><div class="metricline"><span>Episodios</span><b>'+(e?.episodes??0)+'</b></div><div class="metricline"><span>Primer toque decidido</span><b>'+(e?.decided??0)+'</b></div><div class="metricline"><span>TP-first</span><b>'+(e?.tp_first??0)+'</b></div></div>'}).join('');
let labels=Object.entries(M.discovery||{});document.getElementById('labgrid').innerHTML=labels.map(([name,v])=>'<div class="discovery"><h3>'+esc(name.replace('label_','').replaceAll('_',' '))+'</h3><table><thead><tr><th>#</th><th>Reglas</th><th>n</th><th>Tasa</th><th>Baseline</th><th>Lift</th><th>1ª mitad</th><th>2ª mitad</th></tr></thead><tbody>'+v.top_stable.map((z,i)=>'<tr><td>'+(i+1)+'</td><td>'+z.rules.map(ruleText).join('<br>')+'</td><td>'+z.n+'</td><td>'+pct(z.rate)+'</td><td>'+pct(z.baseline)+'</td><td>'+Number(z.lift).toFixed(2)+'×</td><td>'+pct(z.first_half?.rate)+'</td><td>'+pct(z.second_half?.rate)+'</td></tr>').join('')+'</tbody></table></div>').join('');
function show(id){if(grid){let main=grid.querySelector('main');if(main)main.style.display='';let aside=grid.querySelector('aside');if(aside)aside.style.display=''}document.querySelectorAll('[data-tabgroup]').forEach(x=>x.style.display=x.dataset.tabgroup===id?'':'none');tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='episodes'){session.forEach(x=>x.style.display='none');document.querySelectorAll('[data-tabgroup="session"]').forEach((x,i)=>{if(i>=4)x.style.display=''})}}
tabs.addEventListener('click',e=>{let b=e.target.closest('button');if(b)show(b.dataset.tab)});
tabs.querySelector('[data-tab="episodes"]').onclick=()=>{document.querySelectorAll('[data-tabgroup]').forEach(x=>x.style.display='none');tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x.dataset.tab==='episodes'));if(header)header.style.display='flex';if(grid){grid.style.display='grid';let main=grid.querySelector('main');if(main)main.style.display='none';let aside=grid.querySelector('aside');if(aside)aside.style.display='block'}if(compare)compare.style.display='block';if(foot)foot.style.display='block'};
show('session');
})();