(function(){
const M=window.RESEARCH_META||{},V=M.prospective_validation||{},root=document.querySelector('.w');if(!root)return;
const esc=x=>String(x??'?').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const pct=x=>x==null?'?':(100*(+x)).toFixed(1)+'%';
const money=x=>x==null?'?':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(+x);
const ruleText=r=>r.feature?esc(r.feature)+' '+esc(r.op)+' '+esc(r.value):Object.entries(r).map(([k,v])=>esc(k)+' = '+esc(v)).join('<br>');
const header=root.querySelector('header'),cards=root.querySelector('#cards'),grid=root.querySelector('.grid'),compare=document.querySelector('#compare')?.closest('.panel'),foot=root.querySelector('.foot');
const tabs=document.createElement('div');tabs.className='tabs';tabs.innerHTML='<button data-tab="session" class="active">Sesi?n intrad?a</button><button data-tab="episodes">Episodios</button><button data-tab="hyp">Hip?tesis</button><button data-tab="pros">Validaci?n prospectiva</button><button data-tab="lab">Discovery Lab</button>';
root.insertBefore(tabs,root.children[1]);
const banner=document.createElement('div');banner.className='research-banner';banner.innerHTML='<b>Sesi?n de descubrimiento: '+esc(M.discovery_session)+'</b>  ?  Los resultados de esta fecha son diagn?sticos y no cuentan como evidencia prospectiva. H03 est? congelada desde el cierre de esta sesi?n.';root.insertBefore(banner,tabs.nextSibling);
const session=[header,cards,grid].filter(Boolean);session.forEach(x=>x.dataset.tabgroup='session');
const make=(id,html)=>{let d=document.createElement('div');d.className='tabpage';d.dataset.tabgroup=id;d.innerHTML=html;root.appendChild(d);return d};
const episodes=make('episodes','');const aside=grid?.querySelector('aside');if(aside)episodes.appendChild(aside);if(compare)episodes.appendChild(compare);if(foot)episodes.appendChild(foot);if(grid)grid.style.gridTemplateColumns='1fr';
make('hyp','<div class="panel"><h2>Hip?tesis y candidatos</h2><div class="explain"><b>Separaci?n metodol?gica:</b> H01, H02 y H03 est?n congeladas para evaluaci?n prospectiva. H04/H05 y nuevas ideas permanecen exclusivamente en Discovery Lab hasta un freeze expl?cito.</div><div class="hypgrid" id="hypgrid"></div></div>');
make('pros','<div class="panel"><h2>Validaci?n prospectiva</h2><div class="explain"><b>Regla:</b> esta pesta?a excluye autom?ticamente 2026-10-02 y fechas anteriores. La cuenta virtual parte de $1,000 y H03 usa m?ximo un contrato por episodio, entrada ASK y salida BID seg?n la pol?tica congelada.</div><div class="cards" id="proscards"></div><div id="proscheck" class="panel" style="margin-top:12px"></div><div class="panel" style="margin-top:12px"><h2>Operaciones prospectivas por episodio</h2><div class="compare" id="prostrades"></div></div></div>');
make('lab','<div class="panel"><h2>Discovery Lab</h2><div class="explain"><b>Uso:</b> combinaciones retrospectivas para generar hip?tesis, no para afirmar rendimiento futuro. Baseline = frecuencia del evento; lift = tasa de la combinaci?n / baseline.</div><div id="labgrid"></div></div>');
document.getElementById('hypgrid').innerHTML=(M.hypotheses||[]).map(h=>'<div class="hypcard '+h.kind+'"><div class="hyphead"><b>'+esc(h.id)+'</b><span class="side '+h.side.toLowerCase()+'">'+h.side+'  ?  '+h.horizon_min+'m</span></div><div class="state">'+esc(h.status)+'</div><div class="rules">'+(Array.isArray(h.rules)?h.rules.map(ruleText).join('<br>'):ruleText(h.rules))+'</div>'+(h.discovery_episode?'<div class="metricline"><span>Episodios discovery</span><b>'+h.discovery_episode.tp_first+'/'+h.discovery_episode.tp_sl_decided+' TP-first</b></div>':'')+'</div>').join('');
const account=V.virtual_account||{initial_cash:1000,final_cash:1000,net_pnl:0,ledger:[]},ledger=account.ledger||[],episodesV=V.prospective_episodes||[];
const executed=ledger.filter(x=>x.account_status==='EXECUTED'),tp=executed.filter(x=>x.tp_sl==='TP_FIRST').length,sl=executed.filter(x=>x.tp_sl==='SL_FIRST').length;
const days=[...new Set(episodesV.map(x=>x.decision_date).filter(Boolean))].sort(),ret=account.initial_cash?account.net_pnl/account.initial_cash:0;
document.getElementById('proscards').innerHTML=[
 ['Capital inicial',money(account.initial_cash),'baseline congelado'],
 ['Capital actual',money(account.final_cash),'despu?s de costos'],
 ['P&L acumulado',money(account.net_pnl),pct(ret)+' sobre capital inicial'],
 ['D?as prospectivos',days.length,'sesiones con episodios'],
 ['Episodios',episodesV.length,tp+' TP  ?  '+sl+' SL']
].map(x=>'<div class="card"><div class="lab">'+x[0]+'</div><div class="val">'+x[1]+'</div><div class="hint">'+x[2]+'</div></div>').join('');
const checkpoint=n=>days.length>=n?'<span class="good">? alcanzado</span>':'<span class="hint">○ pendiente</span>';
document.getElementById('proscheck').innerHTML='<h2>Protocolo de validación</h2><div class="metricline"><span>Day 1</span><b>'+checkpoint(1)+'</b></div><div class="metricline"><span>Day 5 · revisión intermedia</span><b>'+checkpoint(5)+'</b></div><div class="metricline"><span>Day 10 · checkpoint principal</span><b>'+checkpoint(10)+'</b></div><div class="hint" style="margin-top:10px">Sin ajuste de umbrales, TP/SL o reglas durante la ventana prospectiva.</div>';
document.getElementById('prostrades').innerHTML=ledger.length?'<table><thead><tr><th>Fecha</th><th>Hora UTC</th><th>Hipótesis</th><th>Side</th><th>Contrato</th><th>ASK</th><th>Resultado</th><th>Estado</th><th>P&L día</th><th>Cuenta</th></tr></thead><tbody>'+ledger.map(x=>'<tr><td>'+esc(x.decision_date)+'</td><td>'+esc((x.start||'').slice(11,16))+'</td><td>'+esc(x.hypothesis)+'</td><td>'+esc((x.side||'').toUpperCase())+'</td><td>'+esc(x.contract)+'</td><td>'+money(x.entry_ask)+'</td><td>'+esc(x.tp_sl)+'</td><td>'+esc(x.account_status)+'</td><td>'+money(x.cash_before_trade)+'</td><td>'+money(x.trade_net_pnl)+'</td><td>'+money(x.trade_fees)+'</td><td>'+money(x.cash_after_trade)+'</td></tr>').join('')+'</tbody></table>':'<div class="sub" style="padding:18px 0">Aún no hay episodios prospectivos. Esto es correcto antes de la primera sesión posterior al freeze.</div>';
document.getElementById('labgrid').innerHTML=Object.entries(M.discovery||{}).map(([name,v])=>'<div class="discovery"><h3>'+esc(name.replace('label_','').replaceAll('_',' '))+'</h3><table><thead><tr><th>#</th><th>Reglas</th><th>n</th><th>Tasa</th><th>Baseline</th><th>Lift</th><th>1ª mitad</th><th>2ª mitad</th></tr></thead><tbody>'+v.top_stable.map((z,i)=>'<tr><td>'+(i+1)+'</td><td>'+z.rules.map(ruleText).join('<br>')+'</td><td>'+z.n+'</td><td>'+pct(z.rate)+'</td><td>'+pct(z.baseline)+'</td><td>'+Number(z.lift).toFixed(2)+'×</td><td>'+pct(z.first_half?.rate)+'</td><td>'+pct(z.second_half?.rate)+'</td></tr>').join('')+'</tbody></table></div>').join('');
function show(id){document.querySelectorAll('[data-tabgroup]').forEach(x=>x.style.display=x.dataset.tabgroup===id?(x.classList.contains('tabpage')?'block':''):'none');tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));}
tabs.addEventListener('click',e=>{let b=e.target.closest('button');if(b)show(b.dataset.tab)});show('session');
})();
